[package]
name = "brokerage-api"
version = "0.2.1"
edition = "2024"
description = "A library for communicating with various brokerage APIs, in order to fetch real-time and historical equity data."
license = "MIT"
repository = "https://github.com/SeanTolino/brokerage-api"
keywords = ["finance", "stocks", "futures", "options", "algotrading"]
categories = ["finance"]

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { version = "1", features = ["full", "sync"] }
tracing = "0.1.41"
base64 = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
anyhow = "1.0.99"
chrono = "0.4.38"
urlencoding = "2.1.3"
tokio-tungstenite = { version = "0.27.0", features = ["rustls-tls-native-roots"] }
rustls = { version = "0.23.31", features = ["aws-lc-rs"] }
futures-util = "0.3.31"

[dev-dependencies]
mockito = "1.2.0"
